services:
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: obsidian_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./config/.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - obsidian_net
  redis:
    image: redis:8.6.0-alpine
    container_name: obsidian_redis
    profiles: ["redis"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - obsidian_net
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REPO: ${REPO}
    container_name: obsidian_bot
    ports:
      - "8080:8080"
    command: ./bot
    env_file:
      - ./config/.env
    environment:
      "REPO": ${REPO}
    volumes:
      - sqlite_data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
        required: false
    restart: unless-stopped
    networks:
      - obsidian_net
volumes:
  rabbitmq_data:
  sqlite_data:
  redis_data:
networks:
  obsidian_net:
    driver: bridge
