version: '3'
tasks:
  redis:
    env:
      REPO: redis
      COMPOSE_PROFILES: redis
    cmds:
      - docker compose down
      - docker compose up --build --force-recreate -d
  sqlite:
    env:
      REPO: sqlite
      COMPOSE_PROFILES: ""
    cmds:
      - docker compose down
      - docker compose up --build --force-recreate -d
  down:
    cmds:
      - docker compose down
  clean:
    cmds:
      - docker compose down -v --rmi all --remove-orphans
  deploy:
    requires:
      vars: [ HOST, REPO ]
    vars:
      USER: "root"
      DEST: "/root/obsiTeleGo"
      REPO: "{{.REPO}}"
    cmds:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags {{.REPO}} -o ./bot ./cmd/main.go
      - >-
        rsync -avz --delete 
        --include='config/'
        --include='config/**'
        --include='bot'
        --filter=':- .gitignore'
        --exclude='.git'
        -e ssh ./ {{.USER}}@{{.HOST}}:{{.DEST}}